### PR TITLE
fix: replace JSONObject quote method with a proper String escape method

### PR DESCRIPTION
**Pull request by MemencioPerez**
I did this because I ran into some problems when trying to pass a String value to a field. I thought about using switch expressions, but since source compatibility is in Java 8 I opted to use else-if blocks. Let me know if there is anything that can be improved.

### CODE REVIEW

**Comment by micartey** [comment]
Did you already test it?

**Comment by MemencioPerez** [comment]
> Did you already test it?

Yes, I have tested it, although I'm not entirely sure if it works with characters other than double quotes or newline. Anyway, I'm attaching the test message and the results of the debugging I did, so you can tell me if it works as intended or any changes need to be made.

### Test message code:

```
        DiscordWebhook webhook = new DiscordWebhook("[REDACTED]");
        EmbedObject embed = new EmbedObject()
                .setAuthor(new Author("Swear filter", "", "https://cdn.discordapp.com/emojis/797067188128186418.webp?size=96&quality=lossless"))
                .setTitle("Alert")
                .setColor(Color.decode("#55FFFF"))
                .setDescription("**Memencio** was detected swearing in the **chat** (1/2)")
                .setFooter(new Footer("Swear filter detection", "https://cdn.discordapp.com/attachments/767495363791028244/1296660625233018910/SkyCraft.png?ex=671318cf&is=6711c74f&hm=e79453d658a7789d255ff002ae25d85292b32679a55862248c2e74f3b76e9521&"))
                .setThumbnail(new Thumbnail("https://cdn.discordapp.com/attachments/767495363791028244/1296660625233018910/SkyCraft.png?ex=671318cf&is=6711c74f&hm=e79453d658a7789d255ff002ae25d85292b32679a55862248c2e74f3b76e9521&"))
                .setTimestamp(OffsetDateTime.now());

        embed.getFields().addAll(new LinkedHashSet<Field>(){{
            add(new Field("Message", " \"This is a \b test string (\\ /)\f that I'm using\nto check if the\rstring escape\tmethod works » 👽 «", true));
            add(new Field("Server", "lobby", true));
        }});

        webhook.getEmbeds().add(embed);
        try {
            webhook.execute();
        } catch (IOException e) {
            throw new RuntimeException(e);
        } finally {
            webhook.getEmbeds().clear();
        }
```

### Raw JSON output:

```
{"tts":false,"embeds":[{"thumbnail":{"url":"https:\/\/cdn.discordapp.com\/attachments\/767495363791028244\/1296660625233018910\/SkyCraft.png?ex=671318cf&is=6711c74f&hm=e79453d658a7789d255ff002ae25d85292b32679a55862248c2e74f3b76e9521&"},"color":5636095,"footer":{"icon_url":"https:\/\/cdn.discordapp.com\/attachments\/767495363791028244\/1296660625233018910\/SkyCraft.png?ex=671318cf&is=6711c74f&hm=e79453d658a7789d255ff002ae25d85292b32679a55862248c2e74f3b76e9521&","text":"Swear filter detection"},"author":{"icon_url":"https:\/\/cdn.discordapp.com\/emojis\/797067188128186418.webp?size=96&quality=lossless","name":"Swear filter","url":""},"description":"**Memencio** was detected swearing in the **chat** (1\/2)","title":"Alert","fields":[{"inline":true,"name":"Message","value":"\ue41f \"This is a \b test string (\\ \/)\f that I'm using\nto check if the\rstring escape\tmethod works \u00bb \ud83d\udc7d \u00ab"},{"inline":true,"name":"Server","value":"lobby"}],"timestamp":"2024-11-06T11:42:24.148-04:00"}]}
```

### Beautified JSON output (as IntelliJ IDEA displays it in the debugger):

```
{
  "tts" : false,
  "embeds" : [ {
    "thumbnail" : {
      "url" : "https://cdn.discordapp.com/attachments/767495363791028244/1296660625233018910/SkyCraft.png?ex=671318cf&is=6711c74f&hm=e79453d658a7789d255ff002ae25d85292b32679a55862248c2e74f3b76e9521&"
    },
    "color" : 5636095,
    "footer" : {
      "icon_url" : "https://cdn.discordapp.com/attachments/767495363791028244/1296660625233018910/SkyCraft.png?ex=671318cf&is=6711c74f&hm=e79453d658a7789d255ff002ae25d85292b32679a55862248c2e74f3b76e9521&",
      "text" : "Swear filter detection"
    },
    "author" : {
      "icon_url" : "https://cdn.discordapp.com/emojis/797067188128186418.webp?size=96&quality=lossless",
      "name" : "Swear filter",
      "url" : ""
    },
    "description" : "**Memencio** was detected swearing in the **chat** (1/2)",
    "title" : "Alert",
    "fields" : [ {
      "inline" : true,
      "name" : "Message",
      "value" : " \"This is a \b test string (\\ /)\f that I'm using\nto check if the\rstring escape\tmethod works » 👽 «"
    }, {
      "inline" : true,
      "name" : "Server",
      "value" : "lobby"
    } ],
    "timestamp" : "2024-11-06T11:42:24.148-04:00"
  } ]
}
```

### Embed sent:

image

**Comment by ghost** [comment]
Nice job @MemencioPerez great fix

**Comment by micartey** [comment]
Sorry for the late merge :D 
Good job

**Pull request merged**
